
name: Push Markdown Article Updates to Social Media

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/**/*.md'
      - 'docs/*.md'

jobs:
  push-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v5

      - name: Send Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}  # ä½¿ç”¨ GitHub Secrets å­˜å‚¨ Webhook URL
        run: |
          curl -H "Content-Type: application/json" -X POST -d '{
            "username": "Job Compass Github Bot",
            "avatar_url": "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png",
            "content": "**ğŸ“¢ New update in repository!**\n\nğŸš€ Repository: **${{ github.repository }}**\nğŸ”„ Commit: `${{ github.sha }}`\nğŸ“ [View changes](https://github.com/${{ github.repository }}/commit/${{ github.sha }})"
          }' $DISCORD_WEBHOOK