name: require-assignee

on:
  pull_request:
    types: [opened, edited, synchronize, assigned, unassigned]
  pull_request_review:
    types: [ submitted, dismissed ]
  workflow_dispatch:

jobs:
  check-assignee:
    name: Require Assignee Check
    runs-on: ubuntu-latest
    steps:
      - name: Fail if no assignee
        run: |
          if [ "${{ toJson(github.event.pull_request.assignees) }}" = "[]" ]; then
            echo "❌ This PR must have at least one assignee."
            exit 1
          fi
          echo "✅ Assignee exists."
